### ISSUE TITLE
Can someone tell me if this is safe? no owners sorry

### ISSUE THREAD

**Issue by Merecule** [Edouard127/FNFBotCPP#1]

**Comment by Edouard127** [comment]
Yes this program is safe, use the latest version

How to use it ?
Make sure the window is centered in the middle
Make sure the window name is Friday Night Funkin', if not install WinSpy++ to edit the window name

The bot work using arrow detection with patern, if the greys keys are moved, it can't detect arrows
finally, make sure the arrows colors are not customised

**Comment by Edouard127** [comment]
That's the goal of open source program by the way
Open source = most of the time safe

**Comment by Edouard127** [comment]
If you don't have any questions or issue, i will close this issue
