### ISSUE TITLE
it doesent work 

### ISSUE THREAD

**Issue by yet66** [Edouard127/FNFBotCPP#3]
![Capture](https://user-images.githubusercontent.com/85257710/127759394-fed0a049-e6bc-4adc-a084-98ab192b0bbe.PNG)

**Comment by Edouard127** [comment]
Make sure to install Cuda 10.0, if you don't have a Nvidia GPU, give me
some time to do a cpu-version
https://developer.nvidia.com/cuda-10.0-download-archive

**Comment by yet66** [comment]
Can you make so it has the files already for if that’s fine

**Comment by yet66** [comment]
So the bot can run

**Comment by Edouard127** [comment]
I can't since the libs, includes and bins are found in the windows path
environment

**Comment by yet66** [comment]
Yeah cause the building thing too much

**Comment by yet66** [comment]
Cause i don’t have a lot of space

**Comment by yet66** [comment]
Or the file it needs you can put it in the download thing so it can work

**Comment by yet66** [comment]
Or can you make it on python

**Comment by Edouard127** [comment]
Please leave this issue open, I will be working on it later (it's currently
1:10 am)

**Comment by yet66** [comment]
Oh ok it’s fine cause I did build the bin and stuff but still nothing

**Comment by Edouard127** [comment]
Building with cmake is only if you wish to help us with coding

Can you try with this version ? 
https://github.com/Edouard127/FNFBotCPP/releases/tag/3.0.0-DEBUG

**Comment by yet66** [comment]
I will try it

**Comment by yet66** [comment]
Do I click source or fnf bot cpp

**Comment by yet66** [comment]
Also do I download cmake

**Comment by yet66** [comment]
![6F8885F9-04DF-4D68-AE85-1DD3AEE809FA](https://user-images.githubusercontent.com/85257710/127775152-675709c5-2c59-43e4-83df-4dd1b7e1396d.png) I don’t have a nvidia gpu so you said you might make a cpu version

**Comment by Edouard127** [comment]
> Do I click source or fnf bot cpp

You can delete FNFBotCPP_3.0
It's a fail
The right one is Source.exe

**Comment by Edouard127** [comment]
Let me update the 3.0.1

**Comment by Edouard127** [comment]
> Also do I download cmake
"Building with cmake is only if you wish to help us with coding"

**Comment by yet66** [comment]
Oh ok

**Comment by yet66** [comment]
Also I don’t have a nvidia gpu is intel or something

**Comment by yet66** [comment]
It says I’m missing nppc64_dll

**Comment by yet66** [comment]
Can also make it c# if you can

**Comment by Edouard127** [comment]
> also can you make it c# if you can

C# does not support OpenCV
And i don,t code in Python

**Comment by Edouard127** [comment]
I will rebuild the whole library without cuda, it can take 3 hours

**Comment by yet66** [comment]
But you can you make a separate application like fnfbot by Kade like the latest version

**Comment by Edouard127** [comment]
> But you can you make a separate application like fnfbot by Kade like the latest version

I currently don,t code in C#, i will have some classes soon

**Comment by yet66** [comment]
Cool😁

**Comment by Edouard127** [comment]
What is your current processor ?

**Comment by yet66** [comment]
I will try to make a bot on my own for now

**Comment by yet66** [comment]
Like what do you mean my gpu or cpu

**Comment by Edouard127** [comment]
CPU
For the moment you can use an older version
Which i think does not use cuda
https://github.com/Edouard127/Fnf_bot/releases/tag/2.1.1

**Comment by yet66** [comment]
Also for the new versions do I need a nvidia gpu

**Comment by Edouard127** [comment]
If i manage to build it without cuda, then no you will be able to use it

**Comment by yet66** [comment]
Can you like make a version without needing nvidia gpu cause I can’t really code

**Comment by Edouard127** [comment]
> Can you like make a version without needing nvidia gpu cause I can’t really code

That is exactly what i am talking about

**Comment by yet66** [comment]
Oh ok

**Comment by yet66** [comment]
Do I still need cuda

**Comment by Edouard127** [comment]
> Do I still need cuda
test if this one works
[no_cuda_test.zip](https://github.com/Edouard127/FNFBotCPP/files/6912932/no_cuda_test.zip)

**Comment by yet66** [comment]
It works but it closes immediately

**Comment by Edouard127** [comment]
"### How to use it ?

Make sure the game is called " Friday Night Funkin' "
If its not, download WinSpy++ to edit the window name 

[WinSpy++](http://www.catch22.net/assets/files/software/WinSpy17.zip)
[Tutorial WinSpy++](https://user-images.githubusercontent.com/46357922/125144989-c2806f00-e0ed-11eb-94bd-bd27fa49539a.mp4)

The bot only work if the game is windowed in the middle of the screen
Make sure the arrows colors are not custom"

**Comment by yet66** [comment]
Do I need to download cuda

**Comment by yet66** [comment]
It’s working

**Comment by Edouard127** [comment]
If you don't have any issue you can close this issue
If you have another one you can directly contact me on discord Kamigen^2#1087

**Comment by yet66** [comment]
Oh ok

**Comment by yet66** [comment]
Now ima try the version that’s needs cuda cause I fixed it

**Comment by yet66** [comment]
The one without cuda works but it misses but it fine

**Comment by Edouard127** [comment]
Create a new issue with the label bug

**Comment by yet66** [comment]
Also you can’t add labels it disabled

**Comment by yet66** [comment]
Can you make fnfbot 2.3.4 test without cuba

**Comment by Edouard127** [comment]
Simply move it into the folder you already have

**Comment by yet66** [comment]
Oh ok
